services:
  geth:
    image: ethereum/client-go:stable
    container_name: sepolia-geth
    command:
      - --sepolia                    # 连接到Sepolia测试网
      - --syncmode=snap             # 使用snap同步模式，更快的数据同步
      - --datadir=/data             # 数据存储目录
      - --http                      # 启用HTTP-RPC服务器
      - --http.addr=0.0.0.0         # HTTP-RPC服务器监听地址
      - --http.port=8545            # HTTP-RPC服务器监听端口
      - --http.api=eth,net,web3,debug  # 启用的API模块
      - --authrpc.addr=0.0.0.0      # 认证RPC服务器监听地址
      - --authrpc.port=8551         # 认证RPC服务器监听端口
      - --authrpc.vhosts=*          # 允许所有虚拟主机
      - --authrpc.jwtsecret=/shared/jwtsecret  # JWT密钥文件路径
      - --metrics.expensive         # 启用详细的性能指标
      - --rpc.gascap=50000000      # 设置gas上限为5000万
      - --rpc.txfeecap=1           # 设置交易费用上限为1 ETH
    deploy:
      resources:
        limits:
          cpus: '6'                 # 限制CPU使用为6核
    volumes:
      - ./execution:/data           # 挂载执行层数据目录
      - ./shared-data/jwtsecret:/shared/jwtsecret:ro  # 挂载JWT密钥文件（只读）
    ports:
      - "8545:8545"                # HTTP-RPC端口映射
      - "8551:8551"                # 认证RPC端口映射
      - "30303:30303"              # P2P端口映射
      - "30303:30303/udp"          # P2P UDP端口映射
    restart: unless-stopped         # 容器自动重启策略
    networks:
      - sepolia-net                 # 使用的网络

  prysm:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:latest
    container_name: sepolia-prysm
    command:
      - --sepolia                   # 连接到Sepolia测试网
      - --datadir=/data            # 数据存储目录
      - --execution-endpoint=http://geth:8551  # 执行层客户端地址
      - --jwt-secret=/shared/jwtsecret  # JWT密钥文件路径
      - --accept-terms-of-use      # 接受使用条款
      - --http-host=0.0.0.0        # HTTP服务器监听地址
      - --http-port=3500           # HTTP服务器监听端口
      - --http-modules=prysm,eth   # 启用的API模块
      - --checkpoint-sync-url=https://checkpoint-sync.sepolia.ethpandaops.io  # 检查点同步URL
    deploy:
      resources:
        limits:
          cpus: '1'                # 限制CPU使用为1核
    volumes:
      - ./consensus:/data          # 挂载共识层数据目录
      - ./shared-data/jwtsecret:/shared/jwtsecret:ro  # 挂载JWT密钥文件（只读）
    ports:
      - "3500:3500"               # HTTP API端口映射
      - "13000:13000"             # P2P端口映射
      - "13000:13000/udp"         # P2P UDP端口映射
    restart: unless-stopped        # 容器自动重启策略
    depends_on:
      - geth                       # 依赖geth服务
    networks:
      - sepolia-net                # 使用的网络

networks:
  sepolia-net:
    driver: bridge                 # 使用bridge网络驱动
